In [2]:
def lenghText(text):
    return len(text)
test = input("문자열을 입력하여 주세요")
print(f"당신이 입력한 문자열의 길이는 : {lenghText(test)}")


당신이 입력한 문자열의 길이는 : 8


In [3]:
def reversText(text):
    return print(f"문자열을 거꾸로 : {text[::-1]}")
text = input("문자열을 입력하여 주세요")
reversText(text)

문자열을 거꾸로 : 요세하녕안


In [7]:
def Count(text , word):
    return text.upper().count(word)
text = input("문자열을 입력하여 주세요")
word = input("찾을 문자를 입력하세요")

print(f"문자열에서 {word}의 갯수는 : {Count(text, word)}")

문자열에서 YESTERDAY의 갯수는 : 9


In [8]:
def Count(text):
    content = ""
    content = text.split()
    return len(content)
text = input("문자열을 입력하세요")
print(f"문자열의 단어 갯수는 : {Count(text)}")

문자열의 단어 갯수는 : 10


In [11]:
def Upper_Lower(text):
    swapped = text.swapcase()
    return print(f"대소문자 변환된 문자열 : {swapped}")
text = input("문자열을 입력하세요")
Upper_Lower(text)


대소문자 변환된 문자열 : lIST cOMPREHENSION


In [14]:
def Same_revers(text):
    is_Same = (text == text[::-1])
    return is_Same
text = input("문자열을 입력하세요")

print(f"당신이 작성한 문자열이 회문인가요? : {Same_revers(text)}")

당신이 작성한 문자열이 회문인가요? : True


In [20]:
my_list = list()
my_list.append("사과")
my_list.append("바나나")
my_list.append("체리")
print(f"list추가하기 : {my_list}")
my_list[0] = "오렌지"
print(f"list 수정하기 : {my_list}")
my_list.remove("바나나")
print(f"list 제거하기 : {my_list}")
print(f"list 전체 조회 : {my_list}")
search_item="체리"
if search_item in my_list:
    print(f"{search_item}이/가 리스트에 존재합니다")
else:
    print(f"{search_item}이/가 리스트에 존재하지 않습니다")

list추가하기 : ['사과', '바나나', '체리']
list 수정하기 : ['오렌지', '바나나', '체리']
list 제거하기 : ['오렌지', '체리']
list 전체 조회 : ['오렌지', '체리']
체리이/가 리스트에 존재합니다


In [21]:
duple = ("사과","바나나","체리")
print(f"튜플의 인덱스 1번 값 확인 : {duple[1]}")
search_item = "바나나"
if search_item in duple:
    print(f"{search_item} 이/가 튜플에 있습니다")

튜플의 인덱스 1번 값 확인 : 바나나
바나나 이/가 튜플에 있습니다


In [26]:
setList = set(["수박" , "사과","바나나"])
s = input("과일을 추가하세요")
setList.add(s)
print(f"setList 전체 조회 : {setList}")
setList.remove("사과")
print(f"사과 삭제 : {setList}")
if "바나나" in setList:
    print(f"바나나는 setList에 잇습니다")

setList 전체 조회 : {'체리', '사과', '수박', '바나나'}
사과 삭제 : {'체리', '수박', '바나나'}
바나나는 setList에 잇습니다


In [27]:
student = list(["지성", "채은", "준재"])
name = input("학생 이름을 입력하세요")
student.append(name)
student.remove("준재")
print(f"학생 전체 목록 : {student}")
search_name = input("찾고 싶은 학생 이름")
if search_name in student:
    print(f"{search_name}은 리스트에 있습니다")


학생 전체 목록 : ['지성', '채은', '보경']
지성은 리스트에 있습니다


In [34]:
dic = {"사과" : 6, "바나나":8 , "수박":5}
fruit = input("추가할 상품 이름")
dic[fruit] = 5
print(f"딕셔너리 제품 추가 : {dic}")
dic["사과"]= 10
print(f"딕셔너리 제품 수정 : {dic}")
dic.pop("사과")
print(dic)
if "바나나" in dic.keys():
    print(f"바나나는 딕셔너리에 있습니다.")

딕셔너리 제품 추가 : {'사과': 6, '바나나': 8, '수박': 5, '망고': 5}
딕셔너리 제품 수정 : {'사과': 10, '바나나': 8, '수박': 5, '망고': 5}
{'바나나': 8, '수박': 5, '망고': 5}
바나나는 딕셔너리에 있습니다.


In [35]:
number = list([1,1,2,2,3,3,4,5])
print(f"number : {number}")
number_set = set(number)
print(f"중복된 값 제거 : {number_set}")

number : [1, 1, 2, 2, 3, 3, 4, 5]
중복된 값 제거 : {1, 2, 3, 4, 5}


In [2]:
# **문제 1: 배열 생성 및 변형**
# 1부터 25까지의 숫자를 포함하는 1차원 배열을 만든 후, 이 배열을 5x5 크기의 2차원 배열로 변형하세요
import numpy as np

my_list = np.arange(25)
print(my_list)
my_list2 = my_list.reshape(5,5)
print(my_list2)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
# **문제 2: 배열 슬라이싱**
# 위 1번 문제에서 생성한 5x5 배열에서, 아래 그림과 같이 안쪽에 위치한 3x3 배열(값 7부터 19까지)을 슬라이싱하여 추출하세요.
arr1 = np.arange(25).reshape(5,5)
print(arr1)
arr2 = arr1[1:4, 2:5]
print(f"슬라이싱한 배열 : \n{arr2}")

In [ ]:
# **문제 3: 브로드캐스팅 활용 연산**
# 2x3 크기의 배열 `A = np.array([[5, 10, 15], [20, 25, 30]])`가 있습니다. 이 배열의 첫 번째 행에는 100을, 두 번째 행에는 200을 더하세요. 브로드캐스팅을 활용하여 한 줄의 코드로 해결해 보세요.
# (힌트: `[[100], [200]]` 형태의 배열을 더해야 합니다.)
arr1 = np.array([[5, 10, 15], [20, 25, 30]])
arr2 = np.array([[100],[200]])
result = arr1 + arr2
print(result)

In [ ]:
# **문제 4: 불리언 인덱싱 (필터링)**
# 0부터 15까지의 숫자를 가진 4x4 배열을 만드세요. 이 배열에서 3의 배수만 모두 추출하여 1차원 배열로 만드세요.
arr1 = np.arange(16).reshape(4, 4)
condition = (arr1 % 3 == 0) & arr1 > 0
result = arr1[condition]
print(result)

In [5]:
# **문제 5: 통계 연산 (축 기준)**
# 다음은 4일간 3개 상점의 일일 매출 데이터입니다.
# `sales = np.array([[50, 60, 55], [80, 95, 75], [40, 100, 90], [70, 85, 80]])`
# 각 상점별(열 기준) 평균 매출과 각 날짜별(행 기준) 총매출을 각각 계산하세요.
import pandas as pd
sales = np.array([[50, 60, 55], [80, 95, 75], [40, 100, 90], [70, 85, 80]])
print(f"각 가게의 총매출 : {np.sum(sales, axis=0)}")
print(f"하루 총 매출 : {np.sum(sales, axis=1)}")

df = pd.DataFrame({
    '가게 총 매출': np.sum(sales, axis=0),
    '평균 매출': np.mean(sales, axis=0),
})
df.index = ['성진상화','무당포상회','왕표상회']
print(df)

각 가게의 총매출 : [240 340 300]
하루 총 매출 : [165 250 230 235]
       가게 총 매출  평균 매출
성진상화       240   60.0
무당포상회      340   85.0
왕표상회       300   75.0


In [ ]:
# **문제 6: `np.where` 활용**
# 1부터 10까지의 숫자를 가진 배열에서, 5보다 큰 숫자는 제곱하고, 5보다 작거나 같은 숫자는 0으로 바꾸는 새로운 배열을 생성하세요.
arr1 = np.arange(1,11)
result = np.where(arr1 > 5, arr1*arr1 , 0)
print(result)

In [ ]:
# **문제 7: `argmax` 활용**
# 어떤 선수의 주간 득점 기록이 `scores = np.array([12, 25, 8, 31, 19, 22, 15])`와 같습니다. 이 선수가 가장 높은 득점을 기록한 것은 몇 번째 주(week)인지 찾아내세요. (인덱스는 0부터 시작)
scores = np.array([12, 25, 8, 31, 19, 22, 15])
max_score = np.argmax(scores)
print(f"최고 득점 주(Week) : {max_score}")

In [ ]:
# **문제 8: 배열 합치기**
# `a = np.array([[1, 2], [3, 4]])`와 `b = np.array([[5, 6]])`가 있습니다. `b`를 `a`의 아래에 수직으로 붙여서 3x2 배열을 만드세요.
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
result = np.concatenate((a,b), axis=0)
print(result)

In [ ]:
# **문제 9: 결측치(NaN) 처리**
# 다음 배열에서 결측치(`np.nan`)의 개수를 세고, 결측치를 해당 배열의 전체 평균값(결측치를 제외한)으로 대체하세요.
# `data = np.array([10., 20., np.nan, 30., 40., np.nan, 50.])`